language: go

os:
  - linux

go:
  - 1.2.x
  - 1.3.x
  - 1.4
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

notifications:
  email:
    on_success: change
    on_failure: always
